### ISSUE TITLE
`tags` accross all branches?

### ISSUE THREAD

**Issue by pil0u** [PierreKieffer/tag#1]
https://github.com/PierreKieffer/tag/blob/304790ffcccae7dcb1a87b47156556cacfc0a74c/tag#L33

Following [this discussion on SO](https://stackoverflow.com/questions/4277773/how-to-get-latest-tag-name), you could consider scanning tags across all known branches:
`git describe --abbrev=0 --tags $(git rev-list --tags --max-count=1)`

I'm not sure whether it is desirable or not.

**Comment by PierreKieffer** [comment]
Thank you @pil0u 
Indeed, I usually create a release only from master, (personal habit to maintain a framework in my git workflow).
But the idea is very relevant, and perfectly viable, so you're welcome to create a PR :ok_hand:  !

**Comment by PierreKieffer** [comment]
@pil0u I finally shipped the feature, because it turns out to be very useful 
https://github.com/PierreKieffer/tag/commit/2bd5a03779623179e37b31969f2542f34da9c404
